### ISSUE TITLE
usejsdoc.org not working

### ISSUE THREAD

**Issue by bisvo01** [jsdoc/jsdoc.github.io#191]
Attempting to access [usejsdoc.org](http://usejsdoc.org/) results in the following error message.
404 There isn't a GitHub Pages site here.

**Comment by hegemonic** [comment]
I don't control the domain name `usejsdoc.org`, so unfortunately, I can't fix this. In jsdoc/jsdoc#1642, I asked the owner of the domain name to redirect it to https://jsdoc.app/.

I also removed references to the old URL from this repo.

That's the best I can do, I'm afraid.
